// ════════════════════════════════════════════════════════════════
// AVANÇADO — Técnico Químico
// Para adicionar um módulo novo aqui: escreva getXxxDid()/getXxxQuest()
// e adicione o tile no array TILES_TECNICO, no fim deste arquivo.
// ════════════════════════════════════════════════════════════════
function getSegurancaLabDid(){return`<div class="card"><div class="did-label">Segurança em Laboratório e Manuseio de Reagentes</div><div class="did-intro">Um dos temas mais cobrados em concursos de Técnico Químico: o conhecimento técnico só tem valor se aplicado com segurança. Normas de segurança existem porque muitos acidentes graves em laboratório são <strong>previsíveis e evitáveis</strong>.</div><div class="did-step"><div class="step-n">1</div><div class="step-c"><h4>EPIs obrigatórios</h4><p>Óculos de segurança, jaleco e luvas apropriadas ao reagente manuseado são o mínimo obrigatório em qualquer atividade de laboratório — a escolha da luva, por exemplo, muda conforme o produto (látex não protege contra todos os solventes orgânicos).</p></div></div><div class="did-step"><div class="step-n">2</div><div class="step-c"><h4>Sistema Globalmente Harmonizado (GHS)</h4><p>Padroniza os <strong>pictogramas de risco</strong> em rótulos de produtos químicos (corrosivo, inflamável, tóxico, oxidante, etc), permitindo reconhecer o perigo rapidamente, <strong>independente do idioma</strong> do rótulo — essencial numa indústria com produtos importados.</p></div></div></div><div class="card"><div class="did-label">Armazenamento e descarte</div><div class="did-step"><div class="step-n">3</div><div class="step-c"><h4>Reagentes incompatíveis</h4><p>Substâncias que podem reagir perigosamente entre si nunca devem ser armazenadas juntas: oxidantes fortes separados de combustíveis/redutores; ácidos separados de bases fortes. Um exemplo clássico de pegadinha de concurso: misturar <strong>cloro com amônia</strong> gera gases extremamente tóxicos — os dois nunca devem ficar próximos.</p></div></div><div class="did-step"><div class="step-n">4</div><div class="step-c"><h4>Chuveiro de emergência e lava-olhos</h4><p>Equipamentos obrigatórios em laboratórios que manuseiam produtos corrosivos, permitindo descontaminação <strong>imediata</strong> em caso de contato acidental com pele ou olhos — os primeiros segundos após o acidente são decisivos.</p></div></div><div class="did-step"><div class="step-n">5</div><div class="step-c"><h4>Descarte de resíduos</h4><p>Resíduos químicos <strong>nunca</strong> devem ser descartados diretamente na pia ou no esgoto comum. Devem ser segregados por classe (ácidos, bases, solventes orgânicos, metais pesados) e encaminhados para tratamento adequado, conforme a legislação ambiental vigente.</p></div></div></div>`;}

function getSegurancaLabQuest(){return[{q:'Quais são os EPIs básicos obrigatórios em um laboratório químico?',opts:['Apenas jaleco','Óculos de segurança, jaleco e luvas apropriadas','Somente luvas de látex, para qualquer produto','Nenhum é realmente necessário com experiência'],c:1,res:'<strong>Óculos de segurança, jaleco e luvas apropriadas</strong> ao reagente.'},{q:'O que é o Sistema Globalmente Harmonizado (GHS)?',opts:['Um sistema de medidas de volume','Um sistema padronizado de pictogramas para identificar riscos de produtos químicos','Uma norma só aplicada no Brasil','Um método de titulação'],c:1,res:'<strong>Sistema padronizado de pictogramas</strong> de risco.'},{q:'Por que os pictogramas do GHS são úteis internacionalmente?',opts:['Porque são coloridos','Porque permitem reconhecer o risco rapidamente, independente do idioma do rótulo','Porque substituem a necessidade de EPI','Não têm utilidade real'],c:1,res:'<strong>Permitem reconhecer o risco</strong> independente do idioma.'},{q:'Por que oxidantes fortes devem ser armazenados separados de substâncias combustíveis/redutoras?',opts:['Só por questão de organização visual','Porque juntos podem reagir de forma perigosa, podendo causar incêndio ou explosão','Não há motivo técnico real','Porque ocupam volumes diferentes'],c:1,res:'<strong>Podem reagir perigosamente</strong> entre si.'},{q:'O que acontece se misturarmos cloro com amônia?',opts:['Nada, são compostos inertes entre si','Gera gases extremamente tóxicos','Forma um sal inofensivo','Vira água pura'],c:1,res:'<strong>Gera gases extremamente tóxicos</strong> — nunca devem ficar próximos.'},{q:'Qual a função de um chuveiro de emergência num laboratório?',opts:['Resfriar equipamentos','Descontaminação imediata em caso de contato com produtos corrosivos/perigosos','Limpar vidrarias','Apenas estética, raramente usado'],c:1,res:'<strong>Descontaminação imediata</strong> em caso de acidente.'},{q:'É correto descartar resíduos químicos diretamente na pia comum?',opts:['Sim, sempre','Não — devem ser segregados por classe e tratados adequadamente','Só se forem diluídos com bastante água','Depende só da cor do resíduo'],c:1,res:'<strong>Não</strong> — devem ser segregados e tratados adequadamente.'},{q:'Ácidos e bases fortes devem ser armazenados:',opts:['Sempre juntos, para facilitar o acesso','Separados um do outro','Em qualquer lugar, não importa','Só ácidos precisam de cuidado especial'],c:1,res:'<strong>Separados</strong> um do outro.'},{q:'Qual o principal objetivo das normas de segurança em laboratório?',opts:['Burocratizar o trabalho','Prevenir acidentes e proteger a saúde de quem manuseia os produtos','Aumentar o custo operacional sem benefício real','Impressionar auditores externos'],c:1,res:'<strong>Prevenir acidentes</strong> e proteger a saúde.'}];}

const TILES_TECNICO = [
  { id: 'segurancaLab', emoji: '🥽', label: 'Segurança em Laboratório', sub: 'EPIs, GHS, armazenamento, descarte', xp: 20, did: getSegurancaLabDid(), quest: getSegurancaLabQuest() }
];