// ════════════════════════════════════════════════════════════════
// AVANÇADO — Vigilância Sanitária
// Para adicionar um módulo novo aqui: escreva getXxxDid()/getXxxQuest()
// e adicione o tile no array TILES_VIGILANCIA, no fim deste arquivo.
// ════════════════════════════════════════════════════════════════
function getQualidadeAguaDid(){return`<div class="card"><div class="did-label">Controle de Qualidade da Água</div><div class="did-intro">Garantir que a água chegue potável até a torneira é uma das funções centrais da Vigilância Sanitária. Isso exige monitorar diversos parâmetros físico-químicos e biológicos, todos definidos por legislação específica.</div><div class="did-step"><div class="step-n">1</div><div class="step-c"><h4>Cloração</h4><p>Adição de cloro (ou compostos clorados) à água, com o objetivo de <strong>eliminar micro-organismos patogênicos</strong> — é a etapa de desinfecção padrão nas Estações de Tratamento de Água (ETAs), geralmente realizada após a filtração.</p></div></div><div class="did-step"><div class="step-n">2</div><div class="step-c"><h4>Cloro residual livre</h4><p>É a quantidade mínima de cloro que deve <strong>permanecer</strong> na água após o tratamento — não é só pra desinfetar na ETA, mas pra garantir proteção contínua até a água chegar ao consumidor, evitando recontaminação na tubulação.</p></div></div></div><div class="card"><div class="did-label">Parâmetros de qualidade</div><div class="did-step"><div class="step-n">3</div><div class="step-c"><h4>Faixa de pH</h4><p>Água potável deve ter pH geralmente entre <strong>6,0 e 9,5</strong>. Fora dessa faixa, pode indicar contaminação ou causar problemas de corrosividade/incrustação nas tubulações.</p></div></div><div class="did-step"><div class="step-n">4</div><div class="step-c"><h4>Turbidez</h4><p>Mede a "transparência" da água, relacionada à presença de partículas em suspensão. Água com <strong>alta turbidez</strong> é mais difícil de desinfetar, porque as partículas podem "esconder" micro-organismos da ação do cloro.</p></div></div><div class="did-step"><div class="step-n">5</div><div class="step-c"><h4>Coliformes fecais / E. coli</h4><p>São indicadores biológicos de <strong>contaminação fecal</strong>. A presença deles na água é um forte sinal de risco à saúde — mesmo que outros parâmetros (como pH e turbidez) estejam dentro do normal, a presença de coliformes já reprova a água para consumo.</p></div></div></div>`;}

function getQualidadeAguaQuest(){return[{q:'O que define se uma água é considerada potável?',opts:['Ser transparente apenas','Atender aos padrões estabelecidos pela legislação sanitária','Não ter nenhum sabor','Ter sido fervida uma vez'],c:1,res:'<strong>Atender aos padrões da legislação sanitária.</strong>'},{q:'Qual o objetivo principal da cloração da água?',opts:['Deixar a água mais gelada','Eliminar micro-organismos patogênicos (desinfecção)','Remover partículas sólidas','Corrigir o pH'],c:1,res:'<strong>Eliminar micro-organismos patogênicos.</strong>'},{q:'O que é o "cloro residual livre"?',opts:['O cloro que sobra e é jogado fora','A quantidade mínima de cloro que deve permanecer na água após tratamento, garantindo proteção contínua','Um tipo de poluente','Um erro de medição comum'],c:1,res:'<strong>Quantidade mínima de cloro</strong> que deve permanecer, garantindo proteção contínua.'},{q:'Qual a faixa de pH geralmente aceitável para água potável?',opts:['0 a 3','6,0 a 9,5','10 a 14','Não existe faixa definida'],c:1,res:'<strong>6,0 a 9,5.</strong>'},{q:'O que é turbidez?',opts:['A cor exata da água','Medida da "transparência" da água, relacionada a partículas em suspensão','A temperatura da água','A concentração de sal'],c:1,res:'<strong>Medida da transparência</strong>, relacionada a partículas em suspensão.'},{q:'Por que uma água com alta turbidez é mais difícil de desinfetar?',opts:['Porque fica mais gelada','As partículas em suspensão podem "esconder" micro-organismos da ação do cloro','Porque muda de cor','Não há relação entre os dois'],c:1,res:'<strong>As partículas podem "esconder" micro-organismos</strong> da ação do cloro.'},{q:'O que a presença de coliformes fecais/E. coli na água indica?',opts:['Água muito pura','Contaminação fecal, risco à saúde','Excesso de cloro','Baixa turbidez'],c:1,res:'<strong>Contaminação fecal</strong>, risco à saúde.'},{q:'Por que a presença de coliformes é preocupante mesmo com outros parâmetros normais?',opts:['Não é preocupante, é normal ter um pouco','É um indicador direto de contaminação por fezes, associado a patógenos perigosos','Só importa se o pH também estiver alterado','Coliformes não têm relação com saúde'],c:1,res:'<strong>Indicador direto de contaminação fecal</strong>, associado a patógenos.'},{q:'Em estações de tratamento de água (ETAs), a cloração ocorre geralmente:',opts:['Antes de qualquer outro processo','Na etapa de desinfecção, após a filtração','Só em casos excepcionais','Nunca é usada, é proibida'],c:1,res:'<strong>Na etapa de desinfecção</strong>, após a filtração.'}];}

const TILES_VIGILANCIA = [
  { id: 'qualidadeAgua', emoji: '🚰', label: 'Qualidade da Água', sub: 'cloração, pH, turbidez, coliformes', xp: 20, did: getQualidadeAguaDid(), quest: getQualidadeAguaQuest() }
];