// ════════════════════════════════════════════════════════════════
// AVANÇADO — Engenharia Ambiental
// Para adicionar um módulo novo aqui: escreva getXxxDid()/getXxxQuest()
// e adicione o tile no array TILES_ENGENHARIA, no fim deste arquivo.
// ════════════════════════════════════════════════════════════════
function getTratamentoEfluentesDid(){return`<div class="card"><div class="did-label">Tratamento de Efluentes: DBO e DQO</div><div class="did-intro">Antes de descartar um efluente (água residual industrial ou doméstica) num corpo d'água, é preciso saber o quão "poluído" ele está em termos de matéria orgânica. Duas medidas centrais fazem esse diagnóstico: <strong>DBO</strong> e <strong>DQO</strong>.</div><div class="did-step"><div class="step-n">1</div><div class="step-c"><h4>DBO — Demanda Bioquímica de Oxigênio</h4><p>Mede a quantidade de oxigênio que <strong>micro-organismos consomem</strong> para degradar a matéria orgânica <strong>biodegradável</strong> de uma amostra, geralmente medida ao longo de 5 dias a 20°C (DBO₅,₂₀). Quanto maior a DBO, maior a carga orgânica poluente.</p></div></div><div class="did-step"><div class="step-n">2</div><div class="step-c"><h4>DQO — Demanda Química de Oxigênio</h4><p>Mede o oxigênio necessário para oxidar <strong>quimicamente</strong> toda a matéria orgânica presente — tanto a biodegradável quanto a <strong>não biodegradável</strong>, usando um agente oxidante forte no laboratório. Por isso, a DQO costuma ser <strong>maior</strong> que a DBO no mesmo efluente.</p></div></div><div class="did-step"><div class="step-n">3</div><div class="step-c"><h4>Razão DQO/DBO</h4><p>Usada para avaliar a biodegradabilidade de um efluente: uma razão próxima de <strong>1</strong> indica efluente altamente biodegradável (ótimo para tratamento biológico); uma razão muito alta indica muita matéria não biodegradável, exigindo tratamentos adicionais.</p></div></div></div><div class="card"><div class="did-label">Etapas do tratamento e Eutrofização</div><div class="did-step"><div class="step-n">4</div><div class="step-c"><h4>As 3 etapas do tratamento</h4><p><strong>Primário:</strong> remoção física de sólidos grosseiros (sedimentação).<br><strong>Secundário:</strong> tratamento biológico, usando micro-organismos pra degradar a matéria orgânica (ex: lodos ativados).<br><strong>Terciário:</strong> remoção de nutrientes específicos, desinfecção e "polimento" final antes do descarte.</p></div></div><div class="did-step"><div class="step-n">5</div><div class="step-c"><h4>Eutrofização</h4><p>Efluentes mal tratados, ricos em nutrientes (nitrogênio e fósforo), causam crescimento excessivo de algas num corpo d'água. Quando essas algas morrem, sua decomposição consome grandes quantidades de oxigênio dissolvido na água — podendo causar mortandade de peixes por falta de oxigênio.</p></div></div></div>`;}

function getTratamentoEfluentesQuest(){return[{q:'O que a DBO (Demanda Bioquímica de Oxigênio) mede?',opts:['A temperatura do efluente','O oxigênio consumido por micro-organismos para degradar a matéria orgânica biodegradável','A quantidade de cloro no efluente','O pH do efluente'],c:1,res:'<strong>Oxigênio consumido para degradar matéria orgânica biodegradável.</strong>'},{q:'O que a DQO (Demanda Química de Oxigênio) mede?',opts:['Apenas a matéria orgânica biodegradável','O oxigênio necessário para oxidar quimicamente toda a matéria orgânica, biodegradável e não biodegradável','A cor do efluente','A temperatura de ebulição'],c:1,res:'<strong>Oxigênio para oxidar toda a matéria orgânica</strong>, biodegradável e não.'},{q:'Por que a DQO costuma ser maior que a DBO num mesmo efluente?',opts:['Porque são medidas em unidades diferentes','Porque a DQO também capta a matéria orgânica não biodegradável, que a DBO não mede','Porque a DQO é medida em menos tempo','Não é verdade, são sempre iguais'],c:1,res:'<strong>A DQO também capta a matéria não biodegradável.</strong>'},{q:'Uma razão DQO/DBO próxima de 1 indica que o efluente é:',opts:['Extremamente tóxico','Altamente biodegradável, bom para tratamento biológico','Impossível de tratar','Livre de qualquer matéria orgânica'],c:1,res:'<strong>Altamente biodegradável.</strong>'},{q:'O tratamento primário de efluentes é caracterizado por:',opts:['Tratamento biológico com micro-organismos','Remoção física de sólidos grosseiros (sedimentação)','Desinfecção final','Remoção de nutrientes específicos'],c:1,res:'<strong>Remoção física de sólidos grosseiros.</strong>'},{q:'O tratamento secundário de efluentes é caracterizado por:',opts:['Sedimentação simples apenas','Tratamento biológico, usando micro-organismos para degradar matéria orgânica','Filtração com areia apenas','Adição de cloro apenas'],c:1,res:'<strong>Tratamento biológico</strong> com micro-organismos.'},{q:'O que é eutrofização?',opts:['Purificação natural da água','Crescimento excessivo de algas causado pelo excesso de nutrientes em corpos de água','Um tipo de tratamento terciário','Redução da temperatura da água'],c:1,res:'<strong>Crescimento excessivo de algas</strong> por excesso de nutrientes.'},{q:'Por que a eutrofização pode causar mortandade de peixes?',opts:['As algas liberam veneno diretamente','A decomposição das algas mortas consome o oxigênio dissolvido na água','A água fica ácida demais','Os peixes comem as algas em excesso e morrem'],c:1,res:'<strong>A decomposição consome o oxigênio dissolvido</strong> na água.'},{q:'Qual etapa do tratamento de efluentes normalmente cuida do "polimento final" e desinfecção?',opts:['Primária','Secundária','Terciária','Nenhuma etapa faz isso'],c:2,res:'<strong>Terciária.</strong>'}];}

const TILES_ENGENHARIA = [
  { id: 'tratamentoEfluentes', emoji: '🏭', label: 'Tratamento de Efluentes', sub: 'DBO, DQO, eutrofização', xp: 20, did: getTratamentoEfluentesDid(), quest: getTratamentoEfluentesQuest() }
];